name: me_for_privacy
channels:
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - pandas
  - scikit-learn
  - lifelines
  - python=3.12
  - qtconsole
  - statsmodels
  - tabulate
  - umap-learn
  - jinja2
  - seaborn
prefix: /Users/lona/anaconda3/envs/me_for_privacy
