name: me_for_privacy
channels:
  - defaults
dependencies:
  - matplotlib
  - scikit-learn
  - ipykernel
  - pandas
  - qtconsole
  - statsmodels
  - python=3.12
  - umap-learn
  - lifelines
  - tabulate
prefix: C:\Users\robin\miniconda3\envs\me_for_privacy
