name: me_for_privacy
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0=hd77b12b_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py314h2b7f5b3_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - contourpy=1.3.1=py314h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - expat=2.7.3=h9214b88_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py314h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icu=73.1=h6c2663c_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.8=py314h5da7b33_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.1.1=h827c3e9_0
  - libdeflate=1.22=h2466b09_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libmpdec=4.0.0=h827c3e9_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.6=py314haa95532_1
  - matplotlib-base=3.10.6=py314h7ae407a_1
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py314h0b37514_0
  - mkl_fft=2.1.1=py314h281c9fe_0
  - mkl_random=1.3.0=py314hdbada53_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - numexpr=2.14.1=py314h2592778_0
  - numpy=2.3.4=py314h0be4137_1
  - numpy-base=2.3.4=py314h96ad93d_1
  - openjpeg=2.5.4=h56d5a42_1
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py314haa95532_1
  - pandas=2.3.3=py314hdbada53_1
  - pcre2=10.46=h5740b90_0
  - pillow=11.3.0=py314hb328d1f_0
  - pip=25.2=pyh0d26453_1
  - pixman=0.46.4=h4043f72_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=6.9.1=py314hbb189eb_0
  - pyqt6-sip=13.10.2=py314h630b2a1_0
  - python=3.14.0=h3bc0a5a_101_cp314
  - python-dateutil=2.9.0post0=py314haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=1_cp314
  - pytz=2025.2=py314haa95532_0
  - qtbase=6.9.2=h06bae2a_4
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - setuptools=80.9.0=py314haa95532_0
  - sip=6.12.0=py314h706e071_0
  - six=1.17.0=py314haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py314h827c3e9_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\robin\miniconda3\envs\me_for_privacy
